---
apiVersion: v1
kind: Service
metadata:
  name: go
spec:
  selector:
    app: web-backend-golang
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-backend-golang
  namespace: default
  labels:
    app: web-backend-golang
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-backend-golang
  template:
    metadata:
      labels:
        app: web-backend-golang
    spec:
      containers:
      - name: web-backend-golang
        image: hackerkisteregistry.azurecr.io/go-docker-backend-example:latest
        ports:
        - containerPort: 8080
